#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

stagedFiles=$(git diff --diff-filter=d --cached --name-only)

if [ -n "$stagedFiles" ]; then
  {
    eslint --fix $stagedFiles
    git add $stagedFiles
  }
fi
