name: test
run-name: ${{ github.actor }} as testing command
on: [push]
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Getting the repo code
        uses: actions/checkout@v3
      - name: Installing deps
        working-directory: ./lib
        run: npm i
      - name: Running tests
        working-directory: ./lib
        run: npm run test